Testing Job/Concurrency Separation

diff --git a/.github/workflows/cmake.yml b/.github/workflows/cmake.yml
--- a/.github/workflows/cmake.yml
+++ b/.github/workflows/cmake.yml
@@ -26,6 +26,8 @@ jobs:
 
     runs-on: ${{ matrix.os }}
 
+    # Checkout Code
+    # ==========================================================================================
     steps:
     - name: Checkout code
       uses: actions/checkout@v4
@@ -374,16 +376,16 @@ jobs:
         # Disable debugging output
         set +x  
 
-  # Job: Wordpress (Concurrency)
+  # Job: Wordpress Upload - Demo (Concurrency)
   # ==========================================================================================
   # ==========================================================================================
-  wordpress_upload:
+  wordpress_upload_demo:
 
       strategy:
         matrix:
           os: [macos-latest, windows-latest]
           build_type: [Release]
-          version: [Full, Demo]
+          version: [Demo]
           include:
             - os: windows-latest
               cmake_arch: -A x64
@@ -395,17 +397,36 @@ jobs:
       needs: build  # This ensures that the WordPress upload only runs after the build job completes.
 
       concurrency:
-        group: wordpress-upload-group
+        group: wordpress-upload-group-demo
         cancel-in-progress: false
 
       steps:
+
+        # Checkout Code
+        # ==========================================================================================
         - name: Checkout code
           uses: actions/checkout@v4
-          
+        
 
-        # Upload Installers to WordPress
+
+        # Extract Variables
         # ==========================================================================================
-        - name: Upload Installers to WordPress
+        - name: Extract and Set Configuration Variables
+          id: set-vars
+          run: |
+            echo "Reading configuration from config.cmake..."
+            while IFS=' ' read -r key value
+            do
+              value=$(echo $value | tr -d '"')  # Remove quotes
+              echo "$key=$value" >> $GITHUB_ENV
+            done < <(grep 'set(w' ${GITHUB_WORKSPACE}/config.cmake | sed -e 's/set(//g' -e 's/)//g' -e 's/\s\+/ /g')
+  
+
+
+        # Upload Installers to WordPress (Demo Versions)
+        # ==========================================================================================
+        - name: Upload Demo Installers to WordPress
+          if: matrix.version == 'Demo'
           env:
             WORDPRESS_USERNAME: ${{ secrets.WORDPRESS_USERNAME }}
             WORDPRESS_APPLICATION_PASSWORD: ${{ secrets.WORDPRESS_APPLICATION_PASSWORD }}
@@ -415,82 +436,69 @@ jobs:
             set -x
 
             # Add some spacing for readability
-            echo "\n\n============================================"
+            echo "============================================"
             echo "Starting WordPress Upload Process"
-            echo "============================================\n\n"
+            echo "============================================"
 
             # Ensure required environment variables are set
             if [ -z "$WORDPRESS_USERNAME" ] || [ -z "$WORDPRESS_APPLICATION_PASSWORD" ] || [ -z "$WORDPRESS_SITE" ]; then
-              echo "\nWordPress credentials not set. Skipping WordPress upload step.\n"
+              echo "WordPress credentials not set. Skipping WordPress upload step."
               exit 0
             fi
             
             # Extract the repository name from the GitHub repository environment variable
             REPO_NAME=$(echo $GITHUB_REPOSITORY | awk -F / '{print $2}')
-            echo "\nREPO_NAME set to: $REPO_NAME\n"
+            echo "REPO_NAME set to: $REPO_NAME"
 
-            # Determine the suffix based on the version
-            SUFFIX=""
-            if [ "${{ matrix.version }}" == "Demo" ]; then
-              SUFFIX=".D"
-            fi
+            # Define the suffix for Demo version
+            SUFFIX=".D"
 
-            # Define the file path based on the OS
+            # Define the file path and title based on the OS for Demo versions
             if [ "${{ matrix.os }}" == "macos-latest" ]; then
               FILE_PATH="${{github.workspace}}/build/${REPO_NAME}MacInstaller_${wPROJECT_VERSION}${SUFFIX}.pkg"
-              if [ "${{ matrix.version }}" == "Demo" ]; then
-                FILE_TITLE="${REPO_NAME} Installer v${wPROJECT_VERSION} for Mac (Demo Version)"
-                FILE_DESCRIPTION="${REPO_NAME} Installer v${wPROJECT_VERSION} for Mac (Demo Version)"
-              else
-                FILE_TITLE="${REPO_NAME} Installer v${wPROJECT_VERSION} for Mac"
-                FILE_DESCRIPTION="${REPO_NAME} Installer v${wPROJECT_VERSION} for Mac"
-              fi
+              FILE_TITLE="${REPO_NAME} Installer v${wPROJECT_VERSION} for Mac (Demo Version)"
+              FILE_DESCRIPTION="${REPO_NAME} Installer v${wPROJECT_VERSION} for Mac (Demo Version)"
             elif [ "${{ matrix.os }}" == "windows-latest" ]; then
               FILE_PATH="${{github.workspace}}/build/${REPO_NAME}WinInstaller_${wPROJECT_VERSION}${SUFFIX}.exe"
-              if [ "${{ matrix.version }}" == "Demo" ]; then
-                FILE_TITLE="${REPO_NAME} Installer v${wPROJECT_VERSION} for Windows (Demo Version)"
-                FILE_DESCRIPTION="${REPO_NAME} Installer v${wPROJECT_VERSION} for Windows (Demo Version)"
-              else
-                FILE_TITLE="${REPO_NAME} Installer v${wPROJECT_VERSION} for Windows"
-                FILE_DESCRIPTION="${REPO_NAME} Installer v${wPROJECT_VERSION} for Windows"
-              fi
+              FILE_TITLE="${REPO_NAME} Installer v${wPROJECT_VERSION} for Windows (Demo Version)"
+              FILE_DESCRIPTION="${REPO_NAME} Installer v${wPROJECT_VERSION} for Windows (Demo Version)"
             else
-              echo "\nUnsupported OS for WordPress upload\n"
+              echo "Unsupported OS for WordPress upload"
               exit 1
             fi
 
             # Check if the file exists
             if [ ! -f "$FILE_PATH" ]; then
-              echo "\nFile not found: $FILE_PATH\n"
+              echo "File not found: $FILE_PATH"
               exit 1
             fi
 
             # Check if a file with the same name already exists in WordPress
-            echo "\nChecking if a file with the same name already exists in WordPress...\n"
+            echo "Checking if a file with the same name already exists in WordPress..."
             EXISTING_FILE_RESPONSE=$(curl -s -X GET "${WORDPRESS_SITE}/wp-json/wp/v2/media?search=$(echo ${FILE_TITLE} | sed 's/ /%20/g')" \
               -u "$WORDPRESS_USERNAME:$WORDPRESS_APPLICATION_PASSWORD")
 
-            echo "Existing file response: $EXISTING_FILE_RESPONSE\n"
+            echo "Existing file response: $EXISTING_FILE_RESPONSE"
             EXISTING_FILE_IDS=$(echo "$EXISTING_FILE_RESPONSE" | jq -r '.[].id')
 
             if [ -n "$EXISTING_FILE_IDS" ]; then
-              echo "\nExisting file(s) found. Deleting...\n"
+              echo "Existing file(s) found. Deleting..."
               for FILE_ID in $EXISTING_FILE_IDS; do
                 DELETE_RESPONSE=$(curl -s -X DELETE "${WORDPRESS_SITE}/wp-json/wp/v2/media/${FILE_ID}?force=true" \
                   -u "$WORDPRESS_USERNAME:$WORDPRESS_APPLICATION_PASSWORD")
                 
                 # Check if the deletion was successful
                 if ! echo "$DELETE_RESPONSE" | jq empty; then
-                  echo "\nFailed to delete existing file with ID: $FILE_ID. Response: $DELETE_RESPONSE\n"
+                  echo "Failed to delete existing file with ID: $FILE_ID. Response: $DELETE_RESPONSE"
                   exit 1
                 else
-                  echo "Successfully deleted file with ID: $FILE_ID\n"
+                  echo "Successfully deleted file with ID: $FILE_ID"
                 fi
               done
             fi
 
             # Upload the file to WordPress using CURL
-            echo "\nUploading the file to WordPress...\n"
+            echo "Uploading the file to WordPress..."
             UPLOAD_RESPONSE=$(curl -s -X POST "${WORDPRESS_SITE}/wp-json/wp/v2/media" \
               -u "$WORDPRESS_USERNAME:$WORDPRESS_APPLICATION_PASSWORD" \
               -F "file=@${FILE_PATH}" \
@@ -500,9 +508,9 @@ jobs:
               -F "description=${FILE_DESCRIPTION}")
 
             # Check if the response is a valid JSON
-            echo "Upload response: $UPLOAD_RESPONSE\n"
+            echo "Upload response: $UPLOAD_RESPONSE"
             if ! echo "$UPLOAD_RESPONSE" | jq empty; then
-              echo "\nInvalid JSON response from WordPress: $UPLOAD_RESPONSE\n"
+              echo "Invalid JSON response from WordPress: $UPLOAD_RESPONSE"
               exit 1
             fi
 
@@ -511,31 +519,179 @@ jobs:
             FILE_URL=$(echo "$UPLOAD_RESPONSE" | jq -r '.source_url')
 
             if [ -z "$FILE_URL" ] || [ "$FILE_URL" == "null" ]; then
-              echo "\nFailed to upload file to WordPress\n"
+              echo "Failed to upload file to WordPress"
               echo "$UPLOAD_RESPONSE"
               exit 1
             else
-              echo "\nFile successfully uploaded to WordPress: $FILE_URL\n"
+              echo "File successfully uploaded to WordPress: $FILE_URL"
             fi
-
-            # Set file status to "publish" to ensure it is visible in the media library
-            echo "\nUpdating file status to 'publish'...\n"
-            STATUS_UPDATE_RESPONSE=$(curl -s -X POST "${WORDPRESS_SITE}/wp-json/wp/v2/media/${FILE_ID}" \
-              -u "$WORDPRESS_USERNAME:$WORDPRESS_APPLICATION_PASSWORD" \
-              -d '{"status": "publish"}')
-
-            # Check if the status update was successful
-            if ! echo "$STATUS_UPDATE_RESPONSE" | jq empty; then
-              echo "\nFailed to update file status to 'publish'. Response: $STATUS_UPDATE_RESPONSE\n"
-              exit 1
-            fi
-
-            echo "\nFile status successfully updated to 'publish'.\n"
 
             # Disable verbose debugging output
             set +x
             # Add spacing to indicate the end of the process
-            echo "\n\n============================================"
+            echo "============================================"
             echo "WordPress Upload Process Completed"
-            echo "============================================\n\n"
+            echo "============================================"  
           shell: bash
+
+
+
+
+
+
+
+
+  # Job: Wordpress Upload - Full (Concurrency)
+  # ==========================================================================================
+  # ==========================================================================================
+  wordpress_upload_full:
+
+    strategy:
+      matrix:
+        os: [macos-latest, windows-latest]
+        build_type: [Release]
+        version: [Full]
+        include:
+          - os: windows-latest
+            cmake_arch: -A x64
+          - os: macos-latest
+            cmake_arch: -DCMAKE_OSX_ARCHITECTURES=x86_64
+
+    runs-on: ${{ matrix.os }}
+
+    needs: build  # This ensures that the WordPress upload only runs after the build job completes.
+
+    concurrency:
+      group: wordpress-upload-group-full
+      cancel-in-progress: false
+
+    steps:
+
+      # Checkout Code
+      # ==========================================================================================
+      - name: Checkout code
+        uses: actions/checkout@v4
+      
+
+
+      # Extract Variables
+      # ==========================================================================================
+      - name: Extract and Set Configuration Variables
+        id: set-vars
+        run: |
+          echo "Reading configuration from config.cmake..."
+          while IFS=' ' read -r key value
+          do
+            value=$(echo $value | tr -d '"')  # Remove quotes
+            echo "$key=$value" >> $GITHUB_ENV
+          done < <(grep 'set(w' ${GITHUB_WORKSPACE}/config.cmake | sed -e 's/set(//g' -e 's/)//g' -e 's/\s\+/ /g')
+
+
+
+      # Upload Installers to WordPress (Full Versions)
+      # ==========================================================================================
+      - name: Upload Full Installers to WordPress
+        if: matrix.version == 'Full'
+        env:
+          WORDPRESS_USERNAME: ${{ secrets.WORDPRESS_USERNAME }}
+          WORDPRESS_APPLICATION_PASSWORD: ${{ secrets.WORDPRESS_APPLICATION_PASSWORD }}
+          WORDPRESS_SITE: ${{ secrets.WORDPRESS_SITE }}
+        run: |
+          # Enable verbose debugging output
+          set -x
+
+          # Add some spacing for readability
+          echo "============================================"
+          echo "Starting WordPress Upload Process"
+          echo "============================================"
+
+          # Ensure required environment variables are set
+          if [ -z "$WORDPRESS_USERNAME" ] || [ -z "$WORDPRESS_APPLICATION_PASSWORD" ] || [ -z "$WORDPRESS_SITE" ]; then
+            echo "WordPress credentials not set. Skipping WordPress upload step."
+            exit 0
+          fi
+          
+          # Extract the repository name from the GitHub repository environment variable
+          REPO_NAME=$(echo $GITHUB_REPOSITORY | awk -F / '{print $2}')
+          echo "REPO_NAME set to: $REPO_NAME"
+
+          # Define the file path and title based on the OS for Full versions
+          if [ "${{ matrix.os }}" == "macos-latest" ]; then
+            FILE_PATH="${{github.workspace}}/build/${REPO_NAME}MacInstaller_${wPROJECT_VERSION}.pkg"
+            FILE_TITLE="${REPO_NAME} Installer v${wPROJECT_VERSION} for Mac"
+            FILE_DESCRIPTION="${REPO_NAME} Installer v${wPROJECT_VERSION} for Mac"
+          elif [ "${{ matrix.os }}" == "windows-latest" ]; then
+            FILE_PATH="${{github.workspace}}/build/${REPO_NAME}WinInstaller_${wPROJECT_VERSION}.exe"
+            FILE_TITLE="${REPO_NAME} Installer v${wPROJECT_VERSION} for Windows"
+            FILE_DESCRIPTION="${REPO_NAME} Installer v${wPROJECT_VERSION} for Windows"
+          else
+            echo "Unsupported OS for WordPress upload"
+            exit 1
+          fi
+
+          # Check if the file exists
+          if [ ! -f "$FILE_PATH" ]; then
+            echo "File not found: $FILE_PATH"
+            exit 1
+          fi
+
+          # Check if a file with the same name already exists in WordPress
+          echo "Checking if a file with the same name already exists in WordPress..."
+          EXISTING_FILE_RESPONSE=$(curl -s -X GET "${WORDPRESS_SITE}/wp-json/wp/v2/media?search=$(echo ${FILE_TITLE} | sed 's/ /%20/g')" \
+            -u "$WORDPRESS_USERNAME:$WORDPRESS_APPLICATION_PASSWORD")
+
+          echo "Existing file response: $EXISTING_FILE_RESPONSE"
+          EXISTING_FILE_IDS=$(echo "$EXISTING_FILE_RESPONSE" | jq -r '.[].id')
+
+          if [ -n "$EXISTING_FILE_IDS" ]; then
+            echo "Existing file(s) found. Deleting..."
+            for FILE_ID in $EXISTING_FILE_IDS; do
+              DELETE_RESPONSE=$(curl -s -X DELETE "${WORDPRESS_SITE}/wp-json/wp/v2/media/${FILE_ID}?force=true" \
+                -u "$WORDPRESS_USERNAME:$WORDPRESS_APPLICATION_PASSWORD")
+              
+              # Check if the deletion was successful
+              if ! echo "$DELETE_RESPONSE" | jq empty; then
+                echo "Failed to delete existing file with ID: $FILE_ID. Response: $DELETE_RESPONSE"
+                exit 1
+              else
+                echo "Successfully deleted file with ID: $FILE_ID"
+              fi
+            done
+          fi
+
+          # Upload the file to WordPress using CURL
+          echo "Uploading the file to WordPress..."
+          UPLOAD_RESPONSE=$(curl -s -X POST "${WORDPRESS_SITE}/wp-json/wp/v2/media" \
+            -u "$WORDPRESS_USERNAME:$WORDPRESS_APPLICATION_PASSWORD" \
+            -F "file=@${FILE_PATH}" \
+            -F "title=${FILE_TITLE}" \
+            -F "alt_text=${REPO_NAME} Installer" \
+            -F "caption=Installer for ${REPO_NAME} v${wPROJECT_VERSION}" \
+            -F "description=${FILE_DESCRIPTION}")
+
+          # Check if the response is a valid JSON
+          echo "Upload response: $UPLOAD_RESPONSE"
+          if ! echo "$UPLOAD_RESPONSE" | jq empty; then
+            echo "Invalid JSON response from WordPress: $UPLOAD_RESPONSE"
+            exit 1
+          fi
+
+          # Extract the ID and URL from the response
+          FILE_ID=$(echo "$UPLOAD_RESPONSE" | jq -r '.id')
+          FILE_URL=$(echo "$UPLOAD_RESPONSE" | jq -r '.source_url')
+
+          if [ -z "$FILE_URL" ] || [ "$FILE_URL" == "null" ]; then
+            echo "Failed to upload file to WordPress"
+            echo "$UPLOAD_RESPONSE"
+            exit 1
+          else
+            echo "File successfully uploaded to WordPress: $FILE_URL"
+          fi
+
+          # Disable verbose debugging output
+          set +x
+          # Add spacing to indicate the end of the process
+          echo "============================================"
+          echo "WordPress Upload Process Completed"
+          echo "============================================"  
+        shell: bash
