Testing.

diff --git a/.github/workflows/cmake.yml b/.github/workflows/cmake.yml
--- a/.github/workflows/cmake.yml
+++ b/.github/workflows/cmake.yml
@@ -368,16 +368,8 @@ jobs:
 
 
 
-    # Upload Demo Installers to WordPress
-    # ==========================================================================================
 
-
-
-
-
-
-    
-    # Upload Installers to WordPress.
+    # Upload Installers to WordPress
     # ==========================================================================================
     - name: Upload Installers to WordPress
       env:
@@ -443,16 +435,24 @@ jobs:
         echo "\nChecking if a file with the same name already exists in WordPress...\n"
         EXISTING_FILE_RESPONSE=$(curl -s -X GET "${WORDPRESS_SITE}/wp-json/wp/v2/media?search=$(echo ${FILE_TITLE} | sed 's/ /%20/g')" \
           -u "$WORDPRESS_USERNAME:$WORDPRESS_APPLICATION_PASSWORD")
-        echo "Existing file response: $EXISTING_FILE_RESPONSE\n"
-        EXISTING_FILE_ID=$(echo "$EXISTING_FILE_RESPONSE" | jq -r '.[0].id')
-        EXISTING_FILE_NAME=$(echo "$EXISTING_FILE_RESPONSE" | jq -r '.[0].title.rendered')
 
-        # If the file exists, delete it
-        if [ "$EXISTING_FILE_ID" != "null" ] && [ -n "$EXISTING_FILE_ID" ]; then
-          echo "\nDeleting existing file with ID: $EXISTING_FILE_ID and Name: $EXISTING_FILE_NAME\n"
-          DELETE_RESPONSE=$(curl -s -X DELETE "${WORDPRESS_SITE}/wp-json/wp/v2/media/${EXISTING_FILE_ID}?force=true" \
-            -u "$WORDPRESS_USERNAME:$WORDPRESS_APPLICATION_PASSWORD")
-          echo "Delete response: $DELETE_RESPONSE\n"
+        echo "Existing file response: $EXISTING_FILE_RESPONSE\n"
+        EXISTING_FILE_IDS=$(echo "$EXISTING_FILE_RESPONSE" | jq -r '.[].id')
+
+        if [ -n "$EXISTING_FILE_IDS" ]; then
+          echo "\nExisting file(s) found. Deleting...\n"
+          for FILE_ID in $EXISTING_FILE_IDS; do
+            DELETE_RESPONSE=$(curl -s -X DELETE "${WORDPRESS_SITE}/wp-json/wp/v2/media/${FILE_ID}?force=true" \
+              -u "$WORDPRESS_USERNAME:$WORDPRESS_APPLICATION_PASSWORD")
+            
+            # Check if the deletion was successful
+            if ! echo "$DELETE_RESPONSE" | jq empty; then
+              echo "\nFailed to delete existing file with ID: $FILE_ID. Response: $DELETE_RESPONSE\n"
+              exit 1
+            else
+              echo "Successfully deleted file with ID: $FILE_ID\n"
+            fi
+          done
         fi
 
         # Upload the file to WordPress using CURL
